server:
  port: 24130
spring:
  application:
    name: discussion
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: distcomp
    schema-action: create-if-not-exists
    local-datacenter: datacenter1
  liquibase:
      change-log: db/changelog/main-changelog.yml
